IncomingMessage {
	[0]   _readableState:
	[0]    ReadableState {
	[0]      objectMode: false,
	[0]      highWaterMark: 16384,
	[0]      buffer: BufferList { head: null, tail: null, length: 0 },
	[0]      length: 0,
	[0]      pipes: null,
	[0]      pipesCount: 0,
	[0]      flowing: null,
	[0]      ended: true,
	[0]      endEmitted: false,
	[0]      reading: false,
	[0]      sync: true,
	[0]      needReadable: false,
	[0]      emittedReadable: true,
	[0]      readableListening: false,
	[0]      resumeScheduled: false,
	[0]      destroyed: false,
	[0]      defaultEncoding: 'utf8',
	[0]      awaitDrain: 0,
	[0]      readingMore: true,
	[0]      decoder: null,
	[0]      encoding: null },
	[0]   readable: true,
	[0]   domain: null,
	[0]   _events: {},
	[0]   _eventsCount: 0,
	[0]   _maxListeners: undefined,
	[0]   socket:
	[0]    Socket {
	[0]      connecting: false,
	[0]      _hadError: false,
	[0]      _handle:
	[0]       TCP {
	[0]         reading: true,
	[0]         owner: [Circular],
	[0]         onread: [Function: onread],
	[0]         onconnection: null,
	[0]         writeQueueSize: 0,
	[0]         _consumed: true },
	[0]      _parent: null,
	[0]      _host: null,
	[0]      _readableState:
	[0]       ReadableState {
	[0]         objectMode: false,
	[0]         highWaterMark: 16384,
	[0]         buffer: [Object],
	[0]         length: 0,
	[0]         pipes: null,
	[0]         pipesCount: 0,
	[0]         flowing: true,
	[0]         ended: false,
	[0]         endEmitted: false,
	[0]         reading: true,
	[0]         sync: false,
	[0]         needReadable: true,
	[0]         emittedReadable: false,
	[0]         readableListening: false,
	[0]         resumeScheduled: false,
	[0]         destroyed: false,
	[0]         defaultEncoding: 'utf8',
	[0]         awaitDrain: 0,
	[0]         readingMore: false,
	[0]         decoder: null,
	[0]         encoding: null },
	[0]      readable: true,
	[0]      domain: null,
	[0]      _events:
	[0]       { end: [Array],
	[0]         finish: [Function: onSocketFinish],
	[0]         _socketEnd: [Function: onSocketEnd],
	[0]         drain: [Array],
	[0]         timeout: [Function: socketOnTimeout],
	[0]         data: [Function: bound socketOnData],
	[0]         error: [Function: socketOnError],
	[0]         close: [Array],
	[0]         resume: [Function: onSocketResume],
	[0]         pause: [Function: onSocketPause] },
	[0]      _eventsCount: 10,
	[0]      _maxListeners: undefined,
	[0]      _writableState:
	[0]       WritableState {
	[0]         objectMode: false,
	[0]         highWaterMark: 16384,
	[0]         finalCalled: false,
	[0]         needDrain: false,
	[0]         ending: false,
	[0]         ended: false,
	[0]         finished: false,
	[0]         destroyed: false,
	[0]         decodeStrings: false,
	[0]         defaultEncoding: 'utf8',
	[0]         length: 0,
	[0]         writing: false,
	[0]         corked: 0,
	[0]         sync: true,
	[0]         bufferProcessing: false,
	[0]         onwrite: [Function: bound onwrite],
	[0]         writecb: null,
	[0]         writelen: 0,
	[0]         bufferedRequest: null,
	[0]         lastBufferedRequest: null,
	[0]         pendingcb: 0,
	[0]         prefinished: false,
	[0]         errorEmitted: false,
	[0]         bufferedRequestCount: 0,
	[0]         corkedRequestsFree: [Object] },
	[0]      writable: true,
	[0]      allowHalfOpen: true,
	[0]      _bytesDispatched: 0,
	[0]      _sockname: null,
	[0]      _pendingData: null,
	[0]      _pendingEncoding: '',
	[0]      server:
	[0]       Server {
	[0]         domain: null,
	[0]         _events: [Object],
	[0]         _eventsCount: 2,
	[0]         _maxListeners: undefined,
	[0]         _connections: 2,
	[0]         _handle: [Object],
	[0]         _usingSlaves: false,
	[0]         _slaves: [],
	[0]         _unref: false,
	[0]         allowHalfOpen: true,
	[0]         pauseOnConnect: false,
	[0]         httpAllowHalfOpen: false,
	[0]         timeout: 120000,
	[0]         keepAliveTimeout: 5000,
	[0]         _pendingResponseData: 0,
	[0]         maxHeadersCount: null,
	[0]         _connectionKey: '6::::5000',
	[0]         [Symbol(asyncId)]: 13 },
	[0]      _server:
	[0]       Server {
	[0]         domain: null,
	[0]         _events: [Object],
	[0]         _eventsCount: 2,
	[0]         _maxListeners: undefined,
	[0]         _connections: 2,
	[0]         _handle: [Object],
	[0]         _usingSlaves: false,
	[0]         _slaves: [],
	[0]         _unref: false,
	[0]         allowHalfOpen: true,
	[0]         pauseOnConnect: false,
	[0]         httpAllowHalfOpen: false,
	[0]         timeout: 120000,
	[0]         keepAliveTimeout: 5000,
	[0]         _pendingResponseData: 0,
	[0]         maxHeadersCount: null,
	[0]         _connectionKey: '6::::5000',
	[0]         [Symbol(asyncId)]: 13 },
	[0]      _idleTimeout: 120000,
	[0]      _idleNext:
	[0]       TimersList {
	[0]         _idleNext: [Object],
	[0]         _idlePrev: [Circular],
	[0]         _timer: [Object],
	[0]         _unrefed: true,
	[0]         msecs: 120000,
	[0]         nextTick: false },
	[0]      _idlePrev:
	[0]       Socket {
	[0]         connecting: false,
	[0]         _hadError: false,
	[0]         _handle: [Object],
	[0]         _parent: null,
	[0]         _host: null,
	[0]         _readableState: [Object],
	[0]         readable: true,
	[0]         domain: null,
	[0]         _events: [Object],
	[0]         _eventsCount: 10,
	[0]         _maxListeners: undefined,
	[0]         _writableState: [Object],
	[0]         writable: true,
	[0]         allowHalfOpen: true,
	[0]         _bytesDispatched: 0,
	[0]         _sockname: null,
	[0]         _pendingData: null,
	[0]         _pendingEncoding: '',
	[0]         server: [Object],
	[0]         _server: [Object],
	[0]         _idleTimeout: 120000,
	[0]         _idleNext: [Circular],
	[0]         _idlePrev: [Object],
	[0]         _idleStart: 28141,
	[0]         _destroyed: false,
	[0]         parser: [Object],
	[0]         on: [Function: socketOnWrap],
	[0]         _paused: false,
	[0]         read: [Function],
	[0]         _consuming: true,
	[0]         _httpMessage: [Object],
	[0]         [Symbol(asyncId)]: 314,
	[0]         [Symbol(bytesRead)]: 0,
	[0]         [Symbol(asyncId)]: 315,
	[0]         [Symbol(triggerAsyncId)]: 13 },
	[0]      _idleStart: 28132,
	[0]      _destroyed: false,
	[0]      parser:
	[0]       HTTPParser {
	[0]         '0': [Function: parserOnHeaders],
	[0]         '1': [Function: parserOnHeadersComplete],
	[0]         '2': [Function: parserOnBody],
	[0]         '3': [Function: parserOnMessageComplete],
	[0]         '4': [Function: bound onParserExecute],
	[0]         _headers: [],
	[0]         _url: '',
	[0]         _consumed: true,
	[0]         socket: [Circular],
	[0]         incoming: [Circular],
	[0]         outgoing: null,
	[0]         maxHeaderPairs: 2000,
	[0]         onIncoming: [Function: bound parserOnIncoming] },
	[0]      on: [Function: socketOnWrap],
	[0]      _paused: false,
	[0]      read: [Function],
	[0]      _consuming: true,
	[0]      _httpMessage:
	[0]       ServerResponse {
	[0]         domain: null,
	[0]         _events: [Object],
	[0]         _eventsCount: 1,
	[0]         _maxListeners: undefined,
	[0]         output: [],
	[0]         outputEncodings: [],
	[0]         outputCallbacks: [],
	[0]         outputSize: 0,
	[0]         writable: true,
	[0]         _last: false,
	[0]         upgrading: false,
	[0]         chunkedEncoding: false,
	[0]         shouldKeepAlive: false,
	[0]         useChunkedEncodingByDefault: true,
	[0]         sendDate: true,
	[0]         _removedConnection: false,
	[0]         _removedContLen: false,
	[0]         _removedTE: false,
	[0]         _contentLength: null,
	[0]         _hasBody: true,
	[0]         _trailer: '',
	[0]         finished: false,
	[0]         _headerSent: false,
	[0]         socket: [Circular],
	[0]         connection: [Circular],
	[0]         _header: null,
	[0]         _onPendingData: [Function: bound updateOutgoingData],
	[0]         _sent100: false,
	[0]         _expect_continue: false,
	[0]         req: [Circular],
	[0]         locals: {},
	[0]         writeHead: [Function: writeHead],
	[0]         [Symbol(outHeadersKey)]: [Object] },
	[0]      [Symbol(asyncId)]: 305,
	[0]      [Symbol(bytesRead)]: 0,
	[0]      [Symbol(asyncId)]: 306,
	[0]      [Symbol(triggerAsyncId)]: 13 },
	[0]   connection:
	[0]    Socket {
	[0]      connecting: false,
	[0]      _hadError: false,
	[0]      _handle:
	[0]       TCP {
	[0]         reading: true,
	[0]         owner: [Circular],
	[0]         onread: [Function: onread],
	[0]         onconnection: null,
	[0]         writeQueueSize: 0,
	[0]         _consumed: true },
	[0]      _parent: null,
	[0]      _host: null,
	[0]      _readableState:
	[0]       ReadableState {
	[0]         objectMode: false,
	[0]         highWaterMark: 16384,
	[0]         buffer: [Object],
	[0]         length: 0,
	[0]         pipes: null,
	[0]         pipesCount: 0,
	[0]         flowing: true,
	[0]         ended: false,
	[0]         endEmitted: false,
	[0]         reading: true,
	[0]         sync: false,
	[0]         needReadable: true,
	[0]         emittedReadable: false,
	[0]         readableListening: false,
	[0]         resumeScheduled: false,
	[0]         destroyed: false,
	[0]         defaultEncoding: 'utf8',
	[0]         awaitDrain: 0,
	[0]         readingMore: false,
	[0]         decoder: null,
	[0]         encoding: null },
	[0]      readable: true,
	[0]      domain: null,
	[0]      _events:
	[0]       { end: [Array],
	[0]         finish: [Function: onSocketFinish],
	[0]         _socketEnd: [Function: onSocketEnd],
	[0]         drain: [Array],
					timeout: [Function: socketOnTimeout],
	[0]         data: [Function: bound socketOnData],
	[0]         error: [Function: socketOnError],
	[0]         close: [Array],
	[0]         resume: [Function: onSocketResume],
	[0]         pause: [Function: onSocketPause] },
	[0]      _eventsCount: 10,
	[0]      _maxListeners: undefined,
	[0]      _writableState:
	[0]       WritableState {
	[0]         objectMode: false,
	[0]         highWaterMark: 16384,
	[0]         finalCalled: false,
	[0]         needDrain: false,
	[0]         ending: false,
	[0]         ended: false,
	[0]         finished: false,
	[0]         destroyed: false,
	[0]         decodeStrings: false,
	[0]         defaultEncoding: 'utf8',
	[0]         length: 0,
	[0]         writing: false,
	[0]         corked: 0,
	[0]         sync: true,
	[0]         bufferProcessing: false,
	[0]         onwrite: [Function: bound onwrite],
	[0]         writecb: null,
	[0]         writelen: 0,
	[0]         bufferedRequest: null,
	[0]         lastBufferedRequest: null,
	[0]         pendingcb: 0,
	[0]         prefinished: false,
	[0]         errorEmitted: false,
	[0]         bufferedRequestCount: 0,
	[0]         corkedRequestsFree: [Object] },
	[0]      writable: true,
	[0]      allowHalfOpen: true,
	[0]      _bytesDispatched: 0,
	[0]      _sockname: null,
	[0]      _pendingData: null,
	[0]      _pendingEncoding: '',
	[0]      server:
	[0]       Server {
	[0]         domain: null,
	[0]         _events: [Object],
	[0]         _eventsCount: 2,
	[0]         _maxListeners: undefined,
	[0]         _connections: 2,
	[0]         _handle: [Object],
	[0]         _usingSlaves: false,
	[0]         _slaves: [],
	[0]         _unref: false,
	[0]         allowHalfOpen: true,
	[0]         pauseOnConnect: false,
	[0]         httpAllowHalfOpen: false,
	[0]         timeout: 120000,
	[0]         keepAliveTimeout: 5000,
	[0]         _pendingResponseData: 0,
	[0]         maxHeadersCount: null,
	[0]         _connectionKey: '6::::5000',
	[0]         [Symbol(asyncId)]: 13 },
	[0]      _server:
	[0]       Server {
	[0]         domain: null,
	[0]         _events: [Object],
	[0]         _eventsCount: 2,
	[0]         _maxListeners: undefined,
	[0]         _connections: 2,
	[0]         _handle: [Object],
	[0]         _usingSlaves: false,
	[0]         _slaves: [],
	[0]         _unref: false,
	[0]         allowHalfOpen: true,
	[0]         pauseOnConnect: false,
	[0]         httpAllowHalfOpen: false,
	[0]         timeout: 120000,
	[0]         keepAliveTimeout: 5000,
	[0]         _pendingResponseData: 0,
	[0]         maxHeadersCount: null,
	[0]         _connectionKey: '6::::5000',
	[0]         [Symbol(asyncId)]: 13 },
	[0]      _idleTimeout: 120000,
	[0]      _idleNext:
	[0]       TimersList {
	[0]         _idleNext: [Object],
	[0]         _idlePrev: [Circular],
	[0]         _timer: [Object],
	[0]         _unrefed: true,
	[0]         msecs: 120000,
	[0]         nextTick: false },
	[0]      _idlePrev:
	[0]       Socket {
	[0]         connecting: false,
	[0]         _hadError: false,
	[0]         _handle: [Object],
	[0]         _parent: null,
	[0]         _host: null,
	[0]         _readableState: [Object],
	[0]         readable: true,
	[0]         domain: null,
	[0]         _events: [Object],
	[0]         _eventsCount: 10,
	[0]         _maxListeners: undefined,
	[0]         _writableState: [Object],
	[0]         writable: true,
	[0]         allowHalfOpen: true,
	[0]         _bytesDispatched: 0,
	[0]         _sockname: null,
	[0]         _pendingData: null,
	[0]         _pendingEncoding: '',
	[0]         server: [Object],
	[0]         _server: [Object],
	[0]         _idleTimeout: 120000,
	[0]         _idleNext: [Circular],
	[0]         _idlePrev: [Object],
	[0]         _idleStart: 28141,
	[0]         _destroyed: false,
	[0]         parser: [Object],
	[0]         on: [Function: socketOnWrap],
	[0]         _paused: false,
	[0]         read: [Function],
	[0]         _consuming: true,
	[0]         _httpMessage: [Object],
	[0]         [Symbol(asyncId)]: 314,
	[0]         [Symbol(bytesRead)]: 0,
	[0]         [Symbol(asyncId)]: 315,
	[0]         [Symbol(triggerAsyncId)]: 13 },
	[0]      _idleStart: 28132,
	[0]      _destroyed: false,
	[0]      parser:
	[0]       HTTPParser {
	[0]         '0': [Function: parserOnHeaders],
	[0]         '1': [Function: parserOnHeadersComplete],
	[0]         '2': [Function: parserOnBody],
	[0]         '3': [Function: parserOnMessageComplete],
	[0]         '4': [Function: bound onParserExecute],
	[0]         _headers: [],
	[0]         _url: '',
	[0]         _consumed: true,
	[0]         socket: [Circular],
	[0]         incoming: [Circular],
	[0]         outgoing: null,
	[0]         maxHeaderPairs: 2000,
	[0]         onIncoming: [Function: bound parserOnIncoming] },
	[0]      on: [Function: socketOnWrap],
	[0]      _paused: false,
	[0]      read: [Function],
	[0]      _consuming: true,
	[0]      _httpMessage:
	[0]       ServerResponse {
	[0]         domain: null,
	[0]         _events: [Object],
	[0]         _eventsCount: 1,
	[0]         _maxListeners: undefined,
	[0]         output: [],
	[0]         outputEncodings: [],
	[0]         outputCallbacks: [],
	[0]         outputSize: 0,
	[0]         writable: true,
	[0]         _last: false,
	[0]         upgrading: false,
	[0]         chunkedEncoding: false,
	[0]         shouldKeepAlive: false,
	[0]         useChunkedEncodingByDefault: true,
	[0]         sendDate: true,
	[0]         _removedConnection: false,
	[0]         _removedContLen: false,
	[0]         _removedTE: false,
	[0]         _contentLength: null,
	[0]         _hasBody: true,
	[0]         _trailer: '',
	[0]         finished: false,
	[0]         _headerSent: false,
	[0]         socket: [Circular],
	[0]         connection: [Circular],
	[0]         _header: null,
	[0]         _onPendingData: [Function: bound updateOutgoingData],
	[0]         _sent100: false,
	[0]         _expect_continue: false,
	[0]         req: [Circular],
	[0]         locals: {},
	[0]         writeHead: [Function: writeHead],
	[0]         [Symbol(outHeadersKey)]: [Object] },
	[0]      [Symbol(asyncId)]: 305,
	[0]      [Symbol(bytesRead)]: 0,
	[0]      [Symbol(asyncId)]: 306,
	[0]      [Symbol(triggerAsyncId)]: 13 },
	[0]   httpVersionMajor: 1,
	[0]   httpVersionMinor: 1,
	[0]   httpVersion: '1.1',
	[0]   complete: true,
	[0]   headers:
	[0]    { 'if-none-match': 'W/"df-mLmkYuHSuJopb80H4a74xer1LiM"',
	[0]      cookie: 'olfsk=olfsk5578892595632221; hblid=oPoSa4D09WA7F1oE3m39N0X03JEo03Xa; session=eyJwYXNzcG9ydCI6eyJ1c2VyIjoiNWE3MGMxODM0Zjc0Y2JkNTk2MGMyYzM5In19; session.sig=_NoxpRe7DwvNSwleWWJ09JP6oQk; connect.sid=s%3A_h4P59Zc7Ew0WMra0Q4bfGvqPxyXgDgP.T%2FSstj4MtB5awaWpTx52PpbP2sG1Y1bV4PawWcUMz9A',
	[0]      'accept-language': 'en-US,en;q=0.9',
	[0]      'accept-encoding': 'gzip, deflate, br',
	[0]      referer: 'http://localhost:3000/setup',
	[0]      'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36',
	[0]      accept: 'application/json, text/plain, */*',
	[0]      connection: 'close',
	[0]      host: 'localhost:3000' },
	[0]   rawHeaders:
	[0]    [ 'if-none-match',
	[0]      'W/"df-mLmkYuHSuJopb80H4a74xer1LiM"',
	[0]      'cookie',
	[0]      'olfsk=olfsk5578892595632221; hblid=oPoSa4D09WA7F1oE3m39N0X03JEo03Xa; session=eyJwYXNzcG9ydCI6eyJ1c2VyIjoiNWE3MGMxODM0Zjc0Y2JkNTk2MGMyYzM5In19; session.sig=_NoxpRe7DwvNSwleWWJ09JP6oQk; connect.sid=s%3A_h4P59Zc7Ew0WMra0Q4bfGvqPxyXgDgP.T%2FSstj4MtB5awaWpTx52PpbP2sG1Y1bV4PawWcUMz9A',
	[0]      'accept-language',
	[0]      'en-US,en;q=0.9',
	[0]      'accept-encoding',
	[0]      'gzip, deflate, br',
	[0]      'referer',
	[0]      'http://localhost:3000/setup',
	[0]      'user-agent',
	[0]      'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36',
	[0]      'accept',
	[0]      'application/json, text/plain, */*',
	[0]      'connection',
	[0]      'close',
	[0]      'host',
	[0]      'localhost:3000' ],
	[0]   trailers: {},
	[0]   rawTrailers: [],
	[0]   upgrade: false,
	[0]   url: '/auth/setup',
	[0]   method: 'GET',
	[0]   statusCode: null,
	[0]   statusMessage: null,
	[0]   client:
	[0]    Socket {
	[0]      connecting: false,
	[0]      _hadError: false,
	[0]      _handle:
	[0]       TCP {
	[0]         reading: true,
	[0]         owner: [Circular],
	[0]         onread: [Function: onread],
	[0]         onconnection: null,
	[0]         writeQueueSize: 0,
	[0]         _consumed: true },
	[0]      _parent: null,
	[0]      _host: null,
	[0]      _readableState:
	[0]       ReadableState {
	[0]         objectMode: false,
	[0]         highWaterMark: 16384,
	[0]         buffer: [Object],
	[0]         length: 0,
	[0]         pipes: null,
	[0]         pipesCount: 0,
	[0]         flowing: true,
	[0]         ended: false,
	[0]         endEmitted: false,
	[0]         reading: true,
	[0]         sync: false,
	[0]         needReadable: true,
	[0]         emittedReadable: false,
	[0]         readableListening: false,
	[0]         resumeScheduled: false,
	[0]         destroyed: false,
	[0]         defaultEncoding: 'utf8',
	[0]         awaitDrain: 0,
	[0]         readingMore: false,
	[0]         decoder: null,
	[0]         encoding: null },
	[0]      readable: true,
	[0]      domain: null,
	[0]      _events:
	[0]       { end: [Array],
	[0]         finish: [Function: onSocketFinish],
	[0]         _socketEnd: [Function: onSocketEnd],
	[0]         drain: [Array],
					timeout: [Function: socketOnTimeout],
	[0]         data: [Function: bound socketOnData],
	[0]         error: [Function: socketOnError],
	[0]         close: [Array],
	[0]         resume: [Function: onSocketResume],
	[0]         pause: [Function: onSocketPause] },
	[0]      _eventsCount: 10,
	[0]      _maxListeners: undefined,
	[0]      _writableState:
	[0]       WritableState {
	[0]         objectMode: false,
	[0]         highWaterMark: 16384,
	[0]         finalCalled: false,
	[0]         needDrain: false,
	[0]         ending: false,
	[0]         ended: false,
	[0]         finished: false,
	[0]         destroyed: false,
	[0]         decodeStrings: false,
	[0]         defaultEncoding: 'utf8',
	[0]         length: 0,
	[0]         writing: false,
	[0]         corked: 0,
	[0]         sync: true,
	[0]         bufferProcessing: false,
	[0]         onwrite: [Function: bound onwrite],
	[0]         writecb: null,
	[0]         writelen: 0,
	[0]         bufferedRequest: null,
	[0]         lastBufferedRequest: null,
	[0]         pendingcb: 0,
	[0]         prefinished: false,
	[0]         errorEmitted: false,
	[0]         bufferedRequestCount: 0,
	[0]         corkedRequestsFree: [Object] },
	[0]      writable: true,
	[0]      allowHalfOpen: true,
	[0]      _bytesDispatched: 0,
	[0]      _sockname: null,
	[0]      _pendingData: null,
	[0]      _pendingEncoding: '',
	[0]      server:
	[0]       Server {
	[0]         domain: null,
	[0]         _events: [Object],
	[0]         _eventsCount: 2,
	[0]         _maxListeners: undefined,
	[0]         _connections: 2,
	[0]         _handle: [Object],
	[0]         _usingSlaves: false,
	[0]         _slaves: [],
	[0]         _unref: false,
	[0]         allowHalfOpen: true,
	[0]         pauseOnConnect: false,
	[0]         httpAllowHalfOpen: false,
	[0]         timeout: 120000,
	[0]         keepAliveTimeout: 5000,
	[0]         _pendingResponseData: 0,
	[0]         maxHeadersCount: null,
	[0]         _connectionKey: '6::::5000',
	[0]         [Symbol(asyncId)]: 13 },
	[0]      _server:
	[0]       Server {
	[0]         domain: null,
	[0]         _events: [Object],
	[0]         _eventsCount: 2,
	[0]         _maxListeners: undefined,
	[0]         _connections: 2,
	[0]         _handle: [Object],
	[0]         _usingSlaves: false,
	[0]         _slaves: [],
	[0]         _unref: false,
	[0]         allowHalfOpen: true,
	[0]         pauseOnConnect: false,
	[0]         httpAllowHalfOpen: false,
	[0]         timeout: 120000,
	[0]         keepAliveTimeout: 5000,
	[0]         _pendingResponseData: 0,
	[0]         maxHeadersCount: null,
	[0]         _connectionKey: '6::::5000',
	[0]         [Symbol(asyncId)]: 13 },
	[0]      _idleTimeout: 120000,
	[0]      _idleNext:
	[0]       TimersList {
	[0]         _idleNext: [Object],
	[0]         _idlePrev: [Circular],
	[0]         _timer: [Object],
	[0]         _unrefed: true,
	[0]         msecs: 120000,
	[0]         nextTick: false },
	[0]      _idlePrev:
	[0]       Socket {
	[0]         connecting: false,
	[0]         _hadError: false,
	[0]         _handle: [Object],
	[0]         _parent: null,
	[0]         _host: null,
	[0]         _readableState: [Object],
	[0]         readable: true,
	[0]         domain: null,
	[0]         _events: [Object],
	[0]         _eventsCount: 10,
	[0]         _maxListeners: undefined,
	[0]         _writableState: [Object],
	[0]         writable: true,
	[0]         allowHalfOpen: true,
	[0]         _bytesDispatched: 0,
	[0]         _sockname: null,
	[0]         _pendingData: null,
	[0]         _pendingEncoding: '',
	[0]         server: [Object],
	[0]         _server: [Object],
	[0]         _idleTimeout: 120000,
	[0]         _idleNext: [Circular],
	[0]         _idlePrev: [Object],
	[0]         _idleStart: 28141,
	[0]         _destroyed: false,
	[0]         parser: [Object],
	[0]         on: [Function: socketOnWrap],
	[0]         _paused: false,
	[0]         read: [Function],
	[0]         _consuming: true,
	[0]         _httpMessage: [Object],
	[0]         [Symbol(asyncId)]: 314,
	[0]         [Symbol(bytesRead)]: 0,
	[0]         [Symbol(asyncId)]: 315,
	[0]         [Symbol(triggerAsyncId)]: 13 },
	[0]      _idleStart: 28132,
	[0]      _destroyed: false,
	[0]      parser:
	[0]       HTTPParser {
	[0]         '0': [Function: parserOnHeaders],
	[0]         '1': [Function: parserOnHeadersComplete],
	[0]         '2': [Function: parserOnBody],
	[0]         '3': [Function: parserOnMessageComplete],
	[0]         '4': [Function: bound onParserExecute],
	[0]         _headers: [],
	[0]         _url: '',
	[0]         _consumed: true,
	[0]         socket: [Circular],
	[0]         incoming: [Circular],
	[0]         outgoing: null,
	[0]         maxHeaderPairs: 2000,
	[0]         onIncoming: [Function: bound parserOnIncoming] },
	[0]      on: [Function: socketOnWrap],
	[0]      _paused: false,
	[0]      read: [Function],
	[0]      _consuming: true,
	[0]      _httpMessage:
	[0]       ServerResponse {
	[0]         domain: null,
	[0]         _events: [Object],
	[0]         _eventsCount: 1,
	[0]         _maxListeners: undefined,
	[0]         output: [],
	[0]         outputEncodings: [],
	[0]         outputCallbacks: [],
	[0]         outputSize: 0,
	[0]         writable: true,
	[0]         _last: false,
	[0]         upgrading: false,
	[0]         chunkedEncoding: false,
	[0]         shouldKeepAlive: false,
	[0]         useChunkedEncodingByDefault: true,
	[0]         sendDate: true,
	[0]         _removedConnection: false,
	[0]         _removedContLen: false,
	[0]         _removedTE: false,
	[0]         _contentLength: null,
	[0]         _hasBody: true,
	[0]         _trailer: '',
	[0]         finished: false,
	[0]         _headerSent: false,
	[0]         socket: [Circular],
	[0]         connection: [Circular],
	[0]         _header: null,
	[0]         _onPendingData: [Function: bound updateOutgoingData],
	[0]         _sent100: false,
	[0]         _expect_continue: false,
	[0]         req: [Circular],
	[0]         locals: {},
	[0]         writeHead: [Function: writeHead],
	[0]         [Symbol(outHeadersKey)]: [Object] },
	[0]      [Symbol(asyncId)]: 305,
	[0]      [Symbol(bytesRead)]: 0,
	[0]      [Symbol(asyncId)]: 306,
	[0]      [Symbol(triggerAsyncId)]: 13 },
	[0]   _consuming: false,
	[0]   _dumped: false,
	[0]   next: [Function: next],
	[0]   baseUrl: '',
	[0]   originalUrl: '/auth/setup',
	[0]   _parsedUrl:
	[0]    Url {
	[0]      protocol: null,
	[0]      slashes: null,
	[0]      auth: null,
	[0]      host: null,
	[0]      port: null,
	[0]      hostname: null,
	[0]      hash: null,
	[0]      search: null,
	[0]      query: null,
	[0]      pathname: '/auth/setup',
	[0]      path: '/auth/setup',
	[0]      href: '/auth/setup',
	[0]      _raw: '/auth/setup' },
	[0]   params: {},
	[0]   query: {},
	[0]   res:
	[0]    ServerResponse {
	[0]      domain: null,
	[0]      _events: { finish: [Function: bound resOnFinish] },
	[0]      _eventsCount: 1,
	[0]      _maxListeners: undefined,
	[0]      output: [],
	[0]      outputEncodings: [],
	[0]      outputCallbacks: [],
	[0]      outputSize: 0,
	[0]      writable: true,
	[0]      _last: false,
	[0]      upgrading: false,
	[0]      chunkedEncoding: false,
	[0]      shouldKeepAlive: false,
	[0]      useChunkedEncodingByDefault: true,
	[0]      sendDate: true,
	[0]      _removedConnection: false,
	[0]      _removedContLen: false,
	[0]      _removedTE: false,
	[0]      _contentLength: null,
	[0]      _hasBody: true,
	[0]      _trailer: '',
	[0]      finished: false,
	[0]      _headerSent: false,
	[0]      socket:
	[0]       Socket {
	[0]         connecting: false,
	[0]         _hadError: false,
	[0]         _handle: [Object],
	[0]         _parent: null,
	[0]         _host: null,
	[0]         _readableState: [Object],
	[0]         readable: true,
	[0]         domain: null,
	[0]         _events: [Object],
	[0]         _eventsCount: 10,
	[0]         _maxListeners: undefined,
	[0]         _writableState: [Object],
	[0]         writable: true,
	[0]         allowHalfOpen: true,
	[0]         _bytesDispatched: 0,
	[0]         _sockname: null,
	[0]         _pendingData: null,
	[0]         _pendingEncoding: '',
	[0]         server: [Object],
	[0]         _server: [Object],
	[0]         _idleTimeout: 120000,
	[0]         _idleNext: [Object],
	[0]         _idlePrev: [Object],
	[0]         _idleStart: 28132,
	[0]         _destroyed: false,
	[0]         parser: [Object],
	[0]         on: [Function: socketOnWrap],
	[0]         _paused: false,
	[0]         read: [Function],
	[0]         _consuming: true,
	[0]         _httpMessage: [Circular],
	[0]         [Symbol(asyncId)]: 305,
	[0]         [Symbol(bytesRead)]: 0,
	[0]         [Symbol(asyncId)]: 306,
	[0]         [Symbol(triggerAsyncId)]: 13 },
	[0]      connection:
	[0]       Socket {
	[0]         connecting: false,
	[0]         _hadError: false,
	[0]         _handle: [Object],
	[0]         _parent: null,
	[0]         _host: null,
	[0]         _readableState: [Object],
	[0]         readable: true,
	[0]         domain: null,
	[0]         _events: [Object],
	[0]         _eventsCount: 10,
	[0]         _maxListeners: undefined,
	[0]         _writableState: [Object],
	[0]         writable: true,
	[0]         allowHalfOpen: true,
	[0]         _bytesDispatched: 0,
	[0]         _sockname: null,
	[0]         _pendingData: null,
	[0]         _pendingEncoding: '',
	[0]         server: [Object],
	[0]         _server: [Object],
	[0]         _idleTimeout: 120000,
	[0]         _idleNext: [Object],
	[0]         _idlePrev: [Object],
	[0]         _idleStart: 28132,
	[0]         _destroyed: false,
	[0]         parser: [Object],
	[0]         on: [Function: socketOnWrap],
	[0]         _paused: false,
					read: [Function],
	[0]         _consuming: true,
	[0]         _httpMessage: [Circular],
	[0]         [Symbol(asyncId)]: 305,
	[0]         [Symbol(bytesRead)]: 0,
	[0]         [Symbol(asyncId)]: 306,
	[0]         [Symbol(triggerAsyncId)]: 13 },
	[0]      _header: null,
	[0]      _onPendingData: [Function: bound updateOutgoingData],
	[0]      _sent100: false,
	[0]      _expect_continue: false,
	[0]      req: [Circular],
	[0]      locals: {},
	[0]      writeHead: [Function: writeHead],
	[0]      [Symbol(outHeadersKey)]: { 'x-powered-by': [Array] } },
	[0]   body: {},
	[0]   flash: [Function: _flash],
	[0]   secret: undefined,
	[0]   cookies:
	[0]    { olfsk: 'olfsk5578892595632221',
	[0]      hblid: 'oPoSa4D09WA7F1oE3m39N0X03JEo03Xa',
	[0]      session: 'eyJwYXNzcG9ydCI6eyJ1c2VyIjoiNWE3MGMxODM0Zjc0Y2JkNTk2MGMyYzM5In19',
	[0]      'session.sig': '_NoxpRe7DwvNSwleWWJ09JP6oQk',
	[0]      'connect.sid': 's:_h4P59Zc7Ew0WMra0Q4bfGvqPxyXgDgP.T/Sstj4MtB5awaWpTx52PpbP2sG1Y1bV4PawWcUMz9A' },
	[0]   signedCookies: {},
	[0]   sessionCookies:
	[0]    Cookies {
	[0]      secure: undefined,
	[0]      request: [Circular],
	[0]      response:
	[0]       ServerResponse {
	[0]         domain: null,
	[0]         _events: [Object],
	[0]         _eventsCount: 1,
	[0]         _maxListeners: undefined,
	[0]         output: [],
	[0]         outputEncodings: [],
	[0]         outputCallbacks: [],
	[0]         outputSize: 0,
	[0]         writable: true,
	[0]         _last: false,
	[0]         upgrading: false,
	[0]         chunkedEncoding: false,
	[0]         shouldKeepAlive: false,
	[0]         useChunkedEncodingByDefault: true,
	[0]         sendDate: true,
	[0]         _removedConnection: false,
	[0]         _removedContLen: false,
	[0]         _removedTE: false,
	[0]         _contentLength: null,
	[0]         _hasBody: true,
	[0]         _trailer: '',
	[0]         finished: false,
	[0]         _headerSent: false,
	[0]         socket: [Object],
	[0]         connection: [Object],
	[0]         _header: null,
	[0]         _onPendingData: [Function: bound updateOutgoingData],
	[0]         _sent100: false,
	[0]         _expect_continue: false,
	[0]         req: [Circular],
	[0]         locals: {},
	[0]         writeHead: [Function: writeHead],
	[0]         [Symbol(outHeadersKey)]: [Object] },
	[0]      keys: Keygrip { sign: [Function], verify: [Function], index: [Function] } },
	[0]   sessionOptions: {},
	[0]   sessionKey: 'session',
	[0]   session: [Getter/Setter],
	[0]   _passport:
	[0]    { instance:
	[0]       Authenticator {
	[0]         _key: 'passport',
	[0]         _strategies: [Object],
	[0]         _serializers: [Array],
	[0]         _deserializers: [Array],
	[0]         _infoTransformers: [],
	[0]         _framework: [Object],
	[0]         _userProperty: 'user',
	[0]         _sm: [Object],
	[0]         Authenticator: [Function: Authenticator],
	[0]         Passport: [Function: Authenticator],
	[0]         Strategy: [Object],
	[0]         strategies: [Object] },
	[0]      session: { user: '5a70c1834f74cbd5960c2c39' } },
	[0]   user: { _id: 5a70c1834f74cbd5960c2c39,
	[0]      googleId: '118169853238941565132',
	[0]      email: 'mikeyamato@gmail.com',
	[0]      key: null,
	[0]      __v: 0,
	[0]      credits: 115 },
	[0]   route:
	[0]    Route {
	[0]      path: '/auth/setup',
	[0]      stack: [ [Object], [Object] ],
	[0]      methods: { get: true } } }